### ISSUE TITLE
Question about validation

### ISSUE THREAD

**Issue by escobar5** [EduardoPires/EquinoxProject#1]
Hi,

Thanks for this effort, it is really valuable for a lot of people.

I have a question about validation from some time ago and it applies to this type of architecture. This project is using FluentValidation to specify validation rules on the domain level, and then it uses Data Annotations to specify validation on the application level, is there a way to not specify the validation rules in multiple parts of the application? or is this the recommended way to do it?

**Comment by EduardoPires** [comment]
Hi Escobar! Thank you!

If I can choose I prefer using all validations in an unique point (domain level), but we are working with web development and I think that makes sense of some efforts to avoid unnecessary hits in the server, so the data annotations are useful because they are used in the forms, but the validation in domain level must be required to ensure the data consistency.
