### ISSUE TITLE
how to implement log writing in this architecture?

### ISSUE THREAD

**Issue by pedrofernandesfilho** [EduardoPires/EquinoxProject#110]
how to implement log writing in this architecture?
Is a Cross Cutting?
Could you provide an example?

**Comment by NicoCG** [comment]
Hi @pedrofernandesfilho,

Unfortunately I believe that @EduardoPires will not be doing anymore work on this project as he has not appointed another maintainer and no work has been here for more than two months.

Its sad because multiple people used this project as skeleton template for there own projects.

I could suggest you use project [Skeleton]https://github.com/jej666/Skeleton/tree/master/Skeleton.Infrastructure.Logging there you will find logging implemented but that project has not been maintained for awhile too but you will get an understanding of logging implementation.

**Comment by jedielson** [comment]
Hi @pedrofernandesfilho.

In this project, you can log using [.net core log infrastructure](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1).

If you want to write logs for some another infrastructure, you can combine the native log infra with some third part provider, like [serilog](https://serilog.net/). It's pretty easy, and you should have no problems with that.

In most cases, you can simple configure logging on your startup, but if you need another configuration, the best way is create another project on CrossCutting, put your configuration there and use Startup for load it.

The big goal here, is make use of the native log's infra, because it is well decoupled, and provides good abstractions, allowing you to applying several log layers, according on your needs.

**Comment by pedrofernandesfilho** [comment]
Hi @jedielson!

 Thanks by response.
 I verify that this native log infra is used in the presentation layer. But, what if I need use a log in another layer?

**Comment by jedielson** [comment]
It's a good question, and here it's just my points.

I usually log only on my application boundaries.
So, you can have logs on WebApi, Data (EF, Mongodb, etc), External Services (calls to another HttpServices) and etc.

Never on domain, because domain should be only about business rules, and OOP. Not infra.
If you want to log something that happened on domain, use the IMediator service to notify this event, and use the logger layer (on cross cutting) to properly resolve it.

Now, if you believe it's sooo much hard doing this, I believe the native logging interfaces are still the best option. I wouldn't do in that way, as I've explained, but it's an option.

**Comment by pedrofernandesfilho** [comment]
I'm working on a project that the Solution (.sln) is structured as follows:
 A project for a Windows Service, which has only the logic for running a process periodically (performing multiple treatments on records in a queue).
 This process is in a project that represents the Application layer, which is referenced by the Windows Service project.
 There is a project that represents the business layer (domain) where there are some entities and business rules. This project is referenced by the Application Layer project.

 There is also a project that has the responsibility of doing Dependency Injection.
 This is referenced by the Windows Service project and has reference to other projects.

 And finally, there is a project responsible for data access, where there are some repositories.

 In this scenario, I need to put some log records in the application layer, where there is the process that the service executes.

 From what I am studying and with the help of you (@NicoCG and @jedielson ), it seems to me that a good way would be to have a project responsible for writing the log.
 And to inject, at the application layer, an object that is able to write the log. Is this a good way?
 For this I need an interface on a lower level, application or business.
 Which is more appropriate? Are there any other options? Is this structure adequate?

**Comment by jedielson** [comment]
At application level, I'd go with native infraestructure of asp.net core.

Inject the `ILogger` interface on application services.

Another layer on cross cutting is just for build another log provider, or handle DomainEvents that should be logged.

**Comment by pedrofernandesfilho** [comment]
@jedielson, pelase, can you explain in more detail how to do this injection of the ILogger interface (of .Net Core Framework) in the application layer? If possible with some sample code.

 I have a question that I can not explain myself:
 I think the ILogger interface is not known by the application layer (another project in Solution), so how to do the injection?

 Thanks for the explanations and patience.

**Comment by jedielson** [comment]
Like this.

```

    public class CustomerAppService : ICustomerAppService
    {
        private readonly IMapper _mapper;
        private readonly ICustomerRepository _customerRepository;
        private readonly IEventStoreRepository _eventStoreRepository;
        private readonly IMediatorHandler Bus;
        private readonly ILogger<CustomerAppService> _logger;


    public CustomerAppService(IMapper mapper,
                                  ICustomerRepository customerRepository,
                                  IMediatorHandler bus,
                                  IEventStoreRepository eventStoreRepository,
                                  ILogger<CustomerAppService> logger)
     {
            _mapper = mapper;
            _customerRepository = customerRepository;
            Bus = bus;
            _eventStoreRepository = eventStoreRepository;
            _logger = logger;
     }
```

And on your *.Application.csproj you install the [Microsoft.Extensions.Logging.Abstractions](https://www.nuget.org/packages/Microsoft.Extensions.Logging.Abstractions/)

**Comment by pedrofernandesfilho** [comment]
@jedielson, thanks for the explanation.
