### ISSUE TITLE
Help with Migration

### ISSUE THREAD

**Issue by gang89** [EduardoPires/EquinoxProject#140]
Hi I am getting the following error when running migration:

`Unable to create an object of type 'EquinoxContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728 ---> System.MissingMethodException: No parameterless constructor defined for this object.`

Duplication steps:
1. cd to Equinox.infra.Data folder
2. Run `dotnet ef migrations add InitialCreate --context EquinoxContext --verbose`
3. Encounter error

Please any advise on how to get past this error. Currently using VS Community 8.2.5 on MacOS

**Comment by rhgm** [comment]
Hello,

In NativeInjectorBootStrapper.cs change services.AddScoped<'EquinoxContext'>(); to services.AddDbContext <'EquinoxContext'>();

Same to EventStoreSQLContext.

Hope this helps.

**Comment by carloshenriqueribeiro** [comment]
I resolved by changing the context class.
Now without ctor.
- same to : 
- EventStoreSQLContext and
- ApplicationDbContext

![image](https://user-images.githubusercontent.com/19979749/64134912-94c39400-cdb9-11e9-95a7-bc4bcb99cf4b.png)

**Comment by rafaelfgx** [comment]
Hi,

The error happens because the context class does not have an empty constructor, which makes it impossible for migration to know how to instantiate the class:

![image](https://user-images.githubusercontent.com/7357119/64490737-813f7f80-d236-11e9-8b2c-ff0c73d3a242.png)

To solve it, you can create a class that fabricates the context:

![image](https://user-images.githubusercontent.com/7357119/64490747-a633f280-d236-11e9-94ad-1c2b8b9ae427.png)

**Comment by rafaelfgx** [comment]
> I resolved by changing the context class.
> Now without ctor.
> 
> * same to :
> * EventStoreSQLContext and
> * ApplicationDbContext
> 
> ![image](https://user-images.githubusercontent.com/19979749/64134912-94c39400-cdb9-11e9-95a7-bc4bcb99cf4b.png)

Hi,

Your solution solves the problem because the context class has no constructor.

But the options should be passed via constructor, so it does not create concrete dependency within the class and facilitates tests.
