### ISSUE TITLE
Service should return Domain entity instead of DTO/ViewModel

### ISSUE THREAD

**Issue by a-patel** [EduardoPires/EquinoxProject#49]
Service layer should always return database domain entities instead on DTO/ViewModels.
Do not user mapping (e.g. using automapper) in service, do it in controller instead.

e.g.
CustomerAppService.GetById(x) => Customer
instead of 
CustomerAppService.GetById(x) => CustomerViewModel

**Comment by alexsandro-xpt** [comment]
+1

**Comment by jedielson** [comment]
I respectfully don't agree with this statement.

It goes away from CQRS principle that you should simplify your read models to optimize your queries.
Write models, like Customer don't fit well for queries.

**Comment by thiagolunardi** [comment]
Nothing outside the AppService should know anything about the Domain.

And the Domain entities are not related to "repository/database" entities. In this sample, as we're using EF, and it's really simple demonstration, it's fine. But you should try to avoid create your Entities being concerned about persistence.

**Comment by EduardoPires** [comment]
I disagree. We need to protect our entities. Never receiving or returning your domain models.

**Comment by hugoestevam** [comment]
I get very confused about this topic approach.

Because as per the traditional approach or theory wise, ViewModel should be part of User Interface Layer. At least the name says so.

View models are intended to provide information to and from views and should be specific to the application, as opposed to the general domain. 
For example, what if your system with several other client types, each requiring their own ViewModel. How do you know which ViewModel a method of your application service should return?

Perhaps more appropriately, if you have a separate viewmodel for each view associated with CustomerController, should CustomerAppService have a separate method to return each viewmodel?

I think not...but that does not mean that the Domain should be returned to the Client, the Controller or another layer (Distributed Layer) should handle this.

**Comment by thiagolunardi** [comment]
> View models are intended to provide information to and from views and should be specific to the application, as opposed to the general domain.

Just to increase the accurate: ViewModels just provide data to the view, not otherwise. In this scenario, if the client need to send any data to the application, then this should be made via commands.

the ViewModels, from AppServices, always returns RAW data. if the client - MVC, WebAPi, etc - need to format it's exist - eg. an endpoint just need to return {id,name}, and the RAW is {id,name,address,email}. So the client should have it's own custom format, at client - WebAPI, MVC - side.

So, you're are correct, every app service call can have it's own return.
