### ISSUE TITLE
Alternative project

### ISSUE THREAD

**Issue by nicotravassos** [EduardoPires/EquinoxProject#86]
Does anyone know any alternative projects like this because this project is outdated and it seems that the developer has lost interest in it.

**Comment by jxvalenz** [comment]
I've also been following this project for months. When it was migrated to .NET Core 2.0 I thought this project was going to be very dynamic. It seemed the author was very enthusiastic and committed, but it's been months since we last heard from him. It's unfortunate because being a newbie with these patterns I was really looking forward to version 2.0 so I could learn how to properly implement ES and CQRS with .NET Core in a real-life application.  I have searched for other projects similar to this and they are either outdated or not complete. Eduardo, where are you?

**Comment by TeoDanilo** [comment]
@nicotravassos @jxvalenz 

I don't know if he gave up the project (I do think he'd not), but seen hes facebook I can tell you that he is really busy recently. He have hes own school of programers, He was at MVP Conference this month (and probably was helping on the organization of that event in the previosly weeks). Yesterday he posted that he was named Microsoft Regional Director, what makes him even more busy.
